server:
    port: 8080
---
spring:
    profiles: local
    datasource:
          url: 'jdbc:postgresql://localhost:5432/magneto'
          driver-class-name: 'org.postgresql.Driver'
          username: 'root'
          password: 'root'
          test-on-borrow: true
          validation-query: 'SELECT 1'
          log-validation-errors: true
          max-active: 20
          initial-size: 4
          autoReconnect: true
          autoReconnectForPools: true
          is-connection-validation-required: true
hibernate:
  hbm2ddlAuto: 'create'
  showSql: true
---
spring:
    profiles: production
    jpa:
          daqtabase-platform: org.hibernate.dialect.PostgreSQL94Dialect
    datasource:
#          url: 'jdbc:postgresql://localhost:5432/magneto'
          driver-class-name: 'org.postgresql.Driver'
          username: 'root'
          password: 'root'
          test-on-borrow: true
          validation-query: 'SELECT 1'
          log-validation-errors: true
          max-active: 20
          initial-size: 4
          autoReconnect: true
          autoReconnectForPools: true
          is-connection-validation-required: true
hibernate:
    hbm2ddlAuto: 'update'
    showSql: true